package:
  name: "codetreegen"
  version: "0.2"

# source:
#   git_rev:
#   git_url:

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - astunparse
    - pillow

# test:
#   imports:
#     -

source:
  path: ..

# build:
#   script: python setup.py install

about:
  home: https://github.com/NeKp0T/python/tree/hw1/hw1/codetreegen
  summary: "Generates nice images of your functions' ASTs"
